// src/routes/talks/my-career/slides/AccountSeparationSlide.svelte
<!--
  S6 — Sync: account separation (0:45) · cut-3

  The first of the sync-engine beats. Before, a user account and a calendar
  account were the same object: connect one, and that was the only one you
  ever got. After, the two identities are separate, so a user can connect
  several calendar accounts and sync several calendars from each.

  THE ANIMATION IS ONE MOVE: the calendar account leaves the user account. Flip
  carries the same node out of the box it was nested in, which is the same
  visual sentence the MODULABS gateway and the Playtag seat already taught —
  containment means coupling.

  IT IS GENUINELY UNLIMITED (Brandon, 2026-07-26). An earlier draft showed two
  accounts with two calendars each and no ellipsis, on the theory that the
  tighter claim was the safer one. It was not — it read as a hard limit of two,
  which understates the system. Both ellipses are load-bearing: one inside a
  card for more calendars, one under the stack for more accounts.

  The cards are deliberately smaller than the user-account box. They are the
  repeating element, so they have to look like the start of a list rather than
  like two fixed slots.

  PUBLISH-SAFE: a product capability any user of the app can observe, with no
  internal architecture. Keep it that way — the repo this lives in is public.
-->
<script lang="ts">
	import { onMount, tick } from 'svelte';
	import { loadGsap, EASE, DURATION, reducedMotion } from '$lib/components/deck/gsap';

	let { step = 0, animate = true }: { step?: number; animate?: boolean } = $props();

	// These carry the precision now that the state line above them stopped
	// restating both of them at full length ("any number of ... any number of").
	const notes = [
		'One user can connect any number of calendar accounts',
		'Each connected account can sync any number of calendars',
	];

	let root = $state<HTMLElement>();
	let separated = $state(false);
	let ready = $state(false);
	let applied = -1;

	onMount(async () => {
		const { gsap } = await loadGsap();
		if (root) {
			gsap.set(root.querySelectorAll('.note'), { autoAlpha: 0, y: 6 });
			gsap.set(root.querySelectorAll('.chip, .second'), { autoAlpha: 0 });
		}
		ready = true;
	});

	$effect(() => {
		const target = step;
		if (!ready || target === applied) return;
		applied = target;
		render(target);
	});

	async function render(target: number) {
		const { gsap, Flip } = await loadGsap();
		if (!root) return;

		const still = !animate || reducedMotion();
		const d = still ? 0 : 1;
		const want = target >= 1;

		if (want !== separated) {
			// Capture before Svelte moves the node. The {#if} destroys and recreates
			// it, so data-flip-id is what matches the old position to the new element.
			const state = still ? null : Flip.getState(root.querySelectorAll('[data-flip-id]'));

			separated = want;
			await tick();

			if (state) Flip.from(state, { duration: DURATION, ease: EASE, absolute: true });
		}

		await tick();

		// The second account and the calendars arrive after the move lands, so the
		// slide reads as one thing leaving and then the room it made being used —
		// not as four elements appearing at once.
		gsap.to(root.querySelectorAll('.second'), {
			autoAlpha: want ? 1 : 0,
			duration: DURATION * d,
			ease: EASE,
			delay: want ? DURATION * 0.8 * d : 0,
		});

		gsap.to(root.querySelectorAll('.chip'), {
			autoAlpha: want ? 1 : 0,
			duration: DURATION * 0.8 * d,
			stagger: 0.06 * d,
			ease: EASE,
			delay: want ? DURATION * 1.05 * d : 0,
		});

		gsap.to(root.querySelectorAll('.note'), {
			autoAlpha: want ? 1 : 0,
			y: want ? 0 : 6,
			duration: DURATION * d,
			stagger: 0.07 * d,
			ease: EASE,
			delay: want ? DURATION * 1.3 * d : 0,
		});
	}
</script>

<section class="slide" bind:this={root}>
	<header>
		<p class="company">MOBA &middot; 2025 &ndash; now</p>
		<!--
			NOT "Splitting the calendar from the user" — the two boxes below are
			literally labelled "User account" and "Calendar account", so the headline
			was reading them out. It was also a stage direction for the Flip rather
			than a claim. What the slide argues is that the coupling was the limit:
			one account each was not a scale decision, it was a consequence of the
			two being the same record.

			Short enough to hold one line at the deck's title size — the earlier
			"Separating who you are from what you sync" wrapped to two, and this is
			the only slide in the deck that would have done so.
		-->
		<h1>Coupling was the cap, not scale</h1>
		<p class="state">
			{#if separated}
				After &mdash; one user, many accounts, many calendars
			{:else}
				Before &mdash; the calendar account was the user account
			{/if}
		</p>
	</header>

	<!-- Fixed columns and a reserved height. The right column is empty at step 1
	     on purpose: the space the accounts will occupy is already allocated, so
	     nothing on the left moves when they arrive. -->
	<div class="board">
		<div class="user-box">
			<span class="box-title">User account</span>

			{#if !separated}
				<div class="account nested" data-flip-id="calendar-account">
					<span class="box-title">Calendar account</span>
					<span class="box-note">one, and only ever one</span>
				</div>
			{:else}
				<!-- The box would otherwise sit empty at its reserved height and read
				     as unfinished rather than as deliberately emptied. -->
				<span class="box-note second">identity only &mdash; nothing calendar-shaped left in it</span
				>
			{/if}
		</div>

		<div class="accounts">
			{#if separated}
				<div class="account" data-flip-id="calendar-account">
					<span class="box-title">Calendar account</span>
					<div class="chips">
						<span class="chip">Calendar</span>
						<span class="chip">Calendar</span>
						<span class="chip chip-more">&hellip;</span>
					</div>
				</div>
				<div class="account second">
					<span class="box-title">Calendar account</span>
					<div class="chips">
						<span class="chip">Calendar</span>
						<span class="chip">Calendar</span>
						<span class="chip chip-more">&hellip;</span>
					</div>
				</div>
				<!-- Two cards read as a limit of two. The ellipsis under the stack is
				     what makes it a list. -->
				<span class="more second" aria-label="and more calendar accounts">&hellip;</span>
			{/if}
		</div>
	</div>

	<ul class="notes">
		{#each notes as note (note)}
			<li class="note">{note}</li>
		{/each}
	</ul>
</section>

<style>
	.slide {
		width: 100%;
		max-width: 82rem;
		display: flex;
		flex-direction: column;
		gap: clamp(1.35rem, 3.5vh, 2.25rem);
	}

	.company {
		margin: 0 0 0.4rem;
		font-size: var(--deck-meta);
		letter-spacing: 0.14em;
		text-transform: uppercase;
		opacity: 0.5;
	}

	h1 {
		font-size: var(--deck-title);
		font-weight: 600;
		letter-spacing: -0.02em;
		margin: 0;
	}

	.state {
		margin: 0.4rem 0 0;
		font-size: var(--deck-subtitle);
		opacity: 0.6;
	}

	.board {
		display: grid;
		grid-template-columns: minmax(0, 21rem) minmax(0, 24rem);
		justify-content: start;
		align-items: start;
		column-gap: clamp(1.5rem, 5vw, 4rem);
		/* Reserved for the tallest state — two account boxes — so the slide cannot
		   grow when the second one appears. */
		min-height: clamp(12rem, 27vh, 15.5rem);
	}

	.user-box {
		border: 1px solid color-mix(in srgb, currentColor 30%, transparent);
		border-radius: 6px;
		background: color-mix(in srgb, currentColor 4%, transparent);
		padding: clamp(0.75rem, 1.8vw, 1.1rem);
		display: flex;
		flex-direction: column;
		gap: 0.7rem;
		/* Fixed, or the box shrinks the moment the nested account leaves it and the
		   one element that did not change becomes the one that moves. */
		height: clamp(8.5rem, 19vh, 11rem);
	}

	.accounts {
		display: flex;
		flex-direction: column;
		gap: clamp(0.6rem, 1.5vh, 0.9rem);
	}

	.account {
		border: 1px solid color-mix(in srgb, currentColor 30%, transparent);
		border-radius: 6px;
		background: color-mix(in srgb, currentColor 9%, transparent);
		padding: clamp(0.45rem, 1.1vw, 0.7rem) clamp(0.6rem, 1.4vw, 0.85rem);
		display: flex;
		flex-direction: column;
		gap: 0.35rem;
	}

	/* A step below the user-account box in the type scale. These are the
	   repeating element, so they have to read as list items rather than as peers
	   of the thing they were extracted from. */
	.account .box-title {
		font-size: var(--deck-body);
	}

	/* Nested means coupled — the same visual sentence as the MODULABS gateway and
	   the Playtag seat. The audience has read it twice before this slide. */
	.nested {
		background: color-mix(in srgb, currentColor 9%, transparent);
	}

	.box-title {
		font-size: var(--deck-heading);
		font-weight: 600;
	}

	.box-note {
		font-size: var(--deck-meta);
		opacity: 0.55;
	}

	.chips {
		display: flex;
		flex-wrap: wrap;
		gap: 0.4rem;
	}

	.chip {
		border: 1px solid color-mix(in srgb, currentColor 25%, transparent);
		border-radius: 999px;
		padding: 0.1rem 0.5rem;
		font-size: calc(var(--deck-meta) * 0.9);
		opacity: 0;
		visibility: hidden;
	}

	/* Dashed, because it stands for calendars rather than being one. */
	.chip-more {
		border-style: dashed;
		letter-spacing: 0.08em;
	}

	/* Dimmed with a transparent color rather than `opacity`, because GSAP's
	   autoAlpha drives opacity to 1 on reveal and would erase a CSS opacity. */
	.more {
		font-size: var(--deck-heading);
		letter-spacing: 0.2em;
		padding-left: 0.6rem;
		color: color-mix(in srgb, currentColor 45%, transparent);
	}

	.second {
		visibility: hidden;
		opacity: 0;
	}

	.notes {
		list-style: none;
		margin: 0;
		padding: 0;
		display: flex;
		flex-direction: column;
		gap: 0.4rem;
		font-size: var(--deck-body);
		opacity: 0.85;
	}

	.note {
		padding-left: 1rem;
		position: relative;
		visibility: hidden;
		opacity: 0;
	}

	.note::before {
		content: '';
		position: absolute;
		left: 0;
		top: 0.62em;
		width: 0.4rem;
		height: 1px;
		background: currentColor;
		opacity: 0.5;
	}

	@media (max-width: 760px) {
		.board {
			grid-template-columns: minmax(0, 1fr);
			row-gap: clamp(0.6rem, 1.5vh, 0.9rem);
			min-height: 0;
		}

		.user-box {
			height: auto;
		}
	}
</style>

// next/src/components/deck/AccountSeparationSlide.tsx
'use client';

/**
 * S6 — Sync: account separation (0:45) · cut-3.
 * The React port of `src/routes/talks/my-career/slides/AccountSeparationSlide.svelte`.
 *
 * THE SLIDE'S ARGUMENT IS UNCHANGED and the prose comments that carry it stay
 * with the markup below. What changed is the machinery underneath, and only
 * one part of that is interesting.
 *
 * THE ONE HARD PART: `Flip.getState()` must run BEFORE the DOM moves.
 *
 * Svelte gets this for free. `render()` captures the state, assigns
 * `separated`, and then `await tick()` — a call that means "flush the pending
 * DOM update and come back". Capture, mutate, play, in three statements of one
 * function (`AccountSeparationSlide.svelte:72`, `:75`, `:77`).
 *
 * React has no `tick()`. A state update schedules a render; the DOM changes
 * during the commit that follows, and every effect the component owns runs
 * AFTER that commit. So the naive transcription — capture and play in one
 * effect — captures a rectangle the browser has already moved, and Flip plays
 * a zero-distance animation. It does not throw and it does not warn. It just
 * silently stops animating, which is the same failure class as both live
 * defects found in the PR 2 review (a stale FLIP `from` box, and a missing
 * animation abort).
 *
 * The port therefore splits the three statements across the two phases React
 * actually has:
 *
 *   effect on `step`     capture (the DOM still shows the old nesting here,
 *                        because nothing has re-rendered yet), then setState
 *   layout effect on     the commit has landed and the node has moved; play
 *   `separated`          Flip from the captured state, then run the reveals
 *
 * It is a LAYOUT effect, not a passive one, because a passive effect runs
 * after paint: the browser would show one frame of the node already at its
 * destination before Flip pulled it back to the start. One frame of the
 * finished state is exactly what a Flip animation exists to prevent.
 *
 * STRICTMODE. React 19 double-invokes effects in development. Every tween and
 * every `set` is created inside a `gsap.context()` scoped to the slide root,
 * so the cleanup reverts them and the second mount starts from the same place
 * the first one did. The GSAP loader's module-level memo covers the other half
 * — two mounts await one `registerPlugin`, they do not register twice.
 */

import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';

import { DURATION, EASE, loadGsap, reducedMotion } from '@/deck/gsap';
import { FLIP_OPTIONS, initialSets, planStep, revealTweens } from '@/deck/slide-plan';

type Bundle = Awaited<ReturnType<typeof loadGsap>>;
type FlipState = ReturnType<Bundle['Flip']['getState']>;

/** A layout effect on the client and a passive one during the static export,
 *  which is the standard way to keep React from warning about
 *  `useLayoutEffect` in a render that has no layout to read. */
const useIsomorphicLayoutEffect = typeof window === 'undefined' ? useEffect : useLayoutEffect;

interface Props {
	step?: number;
	animate?: boolean;
}

// These carry the precision now that the state line above them stopped
// restating both of them at full length ("any number of ... any number of").
const NOTES = [
	'One user can connect any number of calendar accounts',
	'Each connected account can sync any number of calendars',
];

export default function AccountSeparationSlide({ step = 0, animate = true }: Props) {
	const root = useRef<HTMLElement | null>(null);
	const bundle = useRef<Bundle | null>(null);
	const context = useRef<ReturnType<Bundle['gsap']['context']> | null>(null);
	const applied = useRef(-1);
	/** The Flip state captured in the pre-mutation phase, waiting for the
	 *  post-commit phase to play it. A ref, not state: writing it must not
	 *  schedule the very render it is trying to measure. */
	const handoff = useRef<{ state: FlipState | null; want: boolean; still: boolean } | null>(null);

	const [separated, setSeparated] = useState(false);
	const [ready, setReady] = useState(false);

	/** Everything GSAP touches goes through the slide's context, so one revert
	 *  undoes the whole slide on unmount. */
	const inContext = useCallback((body: () => void) => {
		const ctx = context.current;
		if (ctx) ctx.add(body);
		else body();
	}, []);

	const runReveals = useCallback(
		(want: boolean, still: boolean) => {
			const element = root.current;
			const loaded = bundle.current;
			if (!element || !loaded) return;

			inContext(() => {
				for (const tween of revealTweens(want, still)) {
					loaded.gsap.to(element.querySelectorAll(tween.selector), tween.vars);
				}
			});
		},
		[inContext],
	);

	useEffect(() => {
		let cancelled = false;

		void (async () => {
			const loaded = await loadGsap();
			if (cancelled || !root.current) return;

			bundle.current = loaded;
			context.current = loaded.gsap.context(() => {
				for (const set of initialSets()) {
					loaded.gsap.set(root.current!.querySelectorAll(set.selector), set.vars);
				}
			}, root);

			setReady(true);
		})();

		return () => {
			cancelled = true;
			context.current?.revert();
			context.current = null;
			// Not the bundle: the loader memo is module-scoped and shared, and
			// clearing this ref would only force a second await on remount.
			applied.current = -1;
		};
	}, []);

	// PHASE 1 — pre-mutation. Nothing has re-rendered for this step yet, so the
	// DOM still shows the nesting the Flip has to animate away FROM.
	useEffect(() => {
		const plan = planStep({
			step,
			applied: applied.current,
			ready,
			separated,
			animate,
			// Read imperatively, exactly as the Svelte original does: this is not
			// reactive there either, so a mid-slide OS change does not retrigger.
			reduced: reducedMotion(),
		});

		if (plan.kind === 'skip') return;
		applied.current = step;

		if (plan.kind === 'reveal') {
			runReveals(plan.want, plan.still);
			return;
		}

		const loaded = bundle.current;
		const element = root.current;
		if (!loaded || !element) return;

		handoff.current = {
			state: plan.capture ? loaded.Flip.getState(element.querySelectorAll('[data-flip-id]')) : null,
			want: plan.want,
			still: plan.still,
		};
		setSeparated(plan.want);
	}, [animate, ready, runReveals, separated, step]);

	// PHASE 2 — post-mutation, pre-paint. The `{#if}` equivalent below has just
	// destroyed and recreated the node; `data-flip-id` is what matches the old
	// position to the new element.
	useIsomorphicLayoutEffect(() => {
		const pending = handoff.current;
		if (!pending) return;
		handoff.current = null;

		const loaded = bundle.current;
		if (loaded && pending.state) {
			inContext(() => loaded.Flip.from(pending.state as FlipState, FLIP_OPTIONS));
		}

		runReveals(pending.want, pending.still);
	}, [inContext, runReveals, separated]);

	return (
		<section className="slide account-separation" ref={root}>
			<header>
				<p className="company">MOBA · 2025 – now</p>
				{/*
					NOT "Splitting the calendar from the user" — the two boxes below are
					literally labelled "User account" and "Calendar account", so the headline
					was reading them out. It was also a stage direction for the Flip rather
					than a claim. What the slide argues is that the coupling was the limit:
					one account each was not a scale decision, it was a consequence of the
					two being the same record.
				*/}
				<h1>Coupling was the cap, not scale</h1>
				<p className="state">
					{separated
						? 'After — one user, many accounts, many calendars'
						: 'Before — the calendar account was the user account'}
				</p>
			</header>

			{/* Fixed columns and a reserved height. The right column is empty at step 1
			    on purpose: the space the accounts will occupy is already allocated, so
			    nothing on the left moves when they arrive. */}
			<div className="board">
				<div className="user-box">
					<span className="box-title">User account</span>

					{!separated ? (
						<div className="account nested" data-flip-id="calendar-account">
							<span className="box-title">Calendar account</span>
							<span className="box-note">one, and only ever one</span>
						</div>
					) : (
						/* The box would otherwise sit empty at its reserved height and read
						   as unfinished rather than as deliberately emptied. */
						<span className="box-note second">
							identity only — nothing calendar-shaped left in it
						</span>
					)}
				</div>

				<div className="accounts">
					{separated && (
						<>
							<div className="account" data-flip-id="calendar-account">
								<span className="box-title">Calendar account</span>
								<div className="chips">
									<span className="chip">Calendar</span>
									<span className="chip">Calendar</span>
									<span className="chip chip-more">…</span>
								</div>
							</div>
							<div className="account second">
								<span className="box-title">Calendar account</span>
								<div className="chips">
									<span className="chip">Calendar</span>
									<span className="chip">Calendar</span>
									<span className="chip chip-more">…</span>
								</div>
							</div>
							{/* Two cards read as a limit of two. The ellipsis under the stack is
							    what makes it a list. */}
							<span className="more second" aria-label="and more calendar accounts">
								…
							</span>
						</>
					)}
				</div>
			</div>

			<ul className="notes">
				{NOTES.map((note) => (
					<li className="note" key={note}>
						{note}
					</li>
				))}
			</ul>
		</section>
	);
}

/** Re-exported so the harness can assert the component and the planner agree
 *  on one duration and one curve rather than two copies of the numbers. */
export { DURATION, EASE };
