// src/lib/components/AboutPage.svelte
<script lang="ts">
	import HeaderControls from '$lib/components/HeaderControls.svelte';
	import { getAboutContent, type AboutLocale } from '$lib/data/about';
	import { m } from '$lib/paraglide/messages';

	let { locale = 'en' }: { locale?: AboutLocale } = $props();

	const content = $derived(getAboutContent(locale));
	const homeHref = $derived(locale === 'ko' ? '/ko' : '/');
	const postsHref = $derived(locale === 'ko' ? '/ko/posts' : '/posts');
	const searchHref = $derived(locale === 'ko' ? '/ko/search' : '/search');
	const systemHref = $derived(locale === 'ko' ? '/ko/system/3b' : '/system/3b');

	const toneClass = {
		accent: 'text-accent',
		foam: 'text-foam',
		gold: 'text-gold',
		rose: 'text-rose',
	};

	function isExternal(href: string): boolean {
		return href.startsWith('http');
	}
</script>

<div class="min-h-screen bg-bg">
	<header class="border-b border-line">
		<div class="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6">
			<a href={homeHref} class="font-mono text-sm font-semibold text-ink no-underline sm:text-base">
				brandonwie.dev
			</a>
			<nav class="flex items-center gap-3 text-sm sm:gap-4">
				<a href={postsHref} class="text-muted no-underline transition-colors hover:text-accent">
					{m.posts_title()}
				</a>
				<a href={systemHref} class="text-muted no-underline transition-colors hover:text-accent">
					3B
				</a>
				<a
					href={searchHref}
					class="text-muted no-underline transition-colors hover:text-accent"
					aria-label={m.search_title()}
				>
					⌕
				</a>
				<HeaderControls />
			</nav>
		</div>
	</header>

	<main class="mx-auto max-w-6xl px-4 py-12 sm:px-6 lg:py-16">
		<section class="grid gap-10 lg:grid-cols-[minmax(0,1.08fr)_minmax(320px,0.92fr)] lg:items-end">
			<div>
				<p class="font-mono text-xs font-semibold uppercase tracking-wider text-faint">
					{content.eyebrow}
				</p>
				<h1
					class="mt-4 max-w-4xl text-4xl font-semibold leading-tight text-ink sm:text-5xl lg:text-6xl"
				>
					{content.title}
				</h1>
				<p class="mt-6 max-w-2xl text-lg leading-8 text-muted">
					{content.subtitle}
				</p>
				<div class="mt-8 flex flex-wrap gap-3">
					{#each content.links as link (link.href)}
						<a
							href={link.href}
							target={link.external ? '_blank' : undefined}
							rel={link.external ? 'noopener noreferrer' : undefined}
							class="rounded border border-line bg-surface px-3 py-2 text-sm text-ink no-underline transition-colors hover:border-accent hover:text-accent"
						>
							{link.label}
						</a>
					{/each}
				</div>
			</div>

			<aside class="border border-line bg-surface p-4">
				<div class="flex items-center justify-between gap-4 border-b border-line pb-3">
					<p class="font-mono text-xs uppercase tracking-wider text-faint">
						{content.visualCaption}
					</p>
					<span class="font-mono text-xs text-accent">live</span>
				</div>
				<div class="mt-5 grid gap-3">
					{#each content.visualLayers as layer, index (layer)}
						<div class="grid grid-cols-[2.5rem_1fr] items-center gap-3">
							<span class="font-mono text-xs text-faint">0{index + 1}</span>
							<div class="h-2 border border-line bg-highlight-low">
								<div
									class="h-full bg-accent"
									style={`width: ${Math.min(42 + index * 12, 92)}%`}
								></div>
							</div>
							<span class="col-start-2 text-sm text-muted">{layer}</span>
						</div>
					{/each}
				</div>
				<div class="mt-6 grid grid-cols-2 gap-3">
					{#each content.metrics as metric (metric.label)}
						<div class="border border-line bg-bg p-3">
							<div class={`font-mono text-xl font-semibold ${toneClass[metric.tone]}`}>
								{metric.value}
							</div>
							<div class="mt-1 text-xs leading-relaxed text-faint">{metric.label}</div>
						</div>
					{/each}
				</div>
			</aside>
		</section>

		<section class="mt-14 grid gap-5 text-base leading-8 text-muted lg:grid-cols-2">
			{#each content.intro as paragraph (paragraph)}
				<p>{paragraph}</p>
			{/each}
		</section>

		<section class="mt-16">
			<h2 class="font-mono text-xs font-semibold uppercase tracking-wider text-faint">
				{content.sections.arc}
			</h2>
			<div class="mt-5 grid gap-4 lg:grid-cols-4">
				{#each content.timeline as item (item.year)}
					<article class="border border-line bg-surface p-5">
						<p class="font-mono text-xs text-accent">{item.year}</p>
						<h3 class="mt-3 text-base font-semibold text-ink">{item.title}</h3>
						<p class="mt-3 text-sm leading-7 text-muted">{item.body}</p>
					</article>
				{/each}
			</div>
		</section>

		<section class="mt-16 grid gap-8 lg:grid-cols-[0.8fr_1.2fr]">
			<div>
				<h2 class="font-mono text-xs font-semibold uppercase tracking-wider text-faint">
					{content.sections.now}
				</h2>
				<p class="mt-4 max-w-sm text-sm leading-7 text-muted">
					{locale === 'ko'
						? '현재의 일은 백엔드 기능 하나가 아니라 운영 가능한 제품 시스템 전체에 가깝습니다.'
						: 'The current work is less about one backend feature and more about the product system that has to keep operating.'}
				</p>
			</div>
			<div class="grid gap-4 sm:grid-cols-3">
				{#each content.now as item (item.title)}
					<article class="border border-line bg-surface p-5">
						<h3 class="text-base font-semibold text-ink">{item.title}</h3>
						<p class="mt-3 text-sm leading-7 text-muted">{item.body}</p>
					</article>
				{/each}
			</div>
		</section>

		<section class="mt-16">
			<h2 class="font-mono text-xs font-semibold uppercase tracking-wider text-faint">
				{content.sections.systems}
			</h2>
			<div class="mt-5 grid gap-4 lg:grid-cols-3">
				{#each content.systems as system (system.title)}
					<a
						href={system.href}
						target={isExternal(system.href) ? '_blank' : undefined}
						rel={isExternal(system.href) ? 'noopener noreferrer' : undefined}
						class="group block overflow-hidden border border-line bg-surface text-ink no-underline transition-colors hover:border-accent"
					>
						<img src={system.image} alt={system.alt} class="aspect-[16/9] w-full object-cover" />
						<div class="p-5">
							<p class="font-mono text-xs uppercase tracking-wider text-faint">{system.kicker}</p>
							<h3 class="mt-2 text-lg font-semibold transition-colors group-hover:text-accent">
								{system.title}
							</h3>
							<p class="mt-3 text-sm leading-7 text-muted">{system.body}</p>
						</div>
					</a>
				{/each}
			</div>
		</section>

		<section class="mt-16 grid gap-6 lg:grid-cols-[1fr_1fr]">
			<div>
				<h2 class="font-mono text-xs font-semibold uppercase tracking-wider text-faint">
					{content.sections.principles}
				</h2>
				<div class="mt-5 grid gap-4">
					{#each content.principles as principle (principle.title)}
						<article class="border-l border-accent bg-surface px-5 py-4">
							<h3 class="text-base font-semibold text-ink">{principle.title}</h3>
							<p class="mt-2 text-sm leading-7 text-muted">{principle.body}</p>
						</article>
					{/each}
				</div>
			</div>

			<div class="border border-line bg-surface p-6">
				<p class="font-mono text-xs uppercase tracking-wider text-gold">
					{content.learning.kicker}
				</p>
				<h2 class="mt-3 text-2xl font-semibold leading-snug text-ink">{content.learning.title}</h2>
				<p class="mt-4 text-sm leading-7 text-muted">{content.learning.body}</p>
				<ul class="mt-5 grid gap-3">
					{#each content.learning.items as item (item)}
						<li class="flex gap-3 text-sm leading-7 text-muted">
							<span class="mt-3 h-1.5 w-1.5 shrink-0 bg-accent"></span>
							<span>{item}</span>
						</li>
					{/each}
				</ul>
			</div>
		</section>
	</main>
</div>

// next/src/components/AboutPage.tsx
import { AppLink } from '@/components/AppLink';
import { aboutCopy } from '@/i18n/copy';
import type { Locale } from '@/i18n/locale';
import { getAboutContent } from '../../../src/lib/data/about';

export interface AboutPageProps {
	locale?: Locale;
}

const toneClass = {
	accent: 'text-accent',
	foam: 'text-foam',
	gold: 'text-gold',
	rose: 'text-rose',
} as const;

function isExternal(href: string): boolean {
	return href.startsWith('http');
}

function SecHead({ label }: { label: string }) {
	return (
		<div className="mb-6 flex items-center gap-3.5">
			<span className="font-mono font-bold text-foam">#</span>
			<h2 className="font-sans text-xl font-semibold tracking-tight text-ink">{label}</h2>
			<span className="h-px flex-1 bg-line2" />
		</div>
	);
}

export function AboutPage({ locale = 'en' }: AboutPageProps) {
	const content = getAboutContent(locale);
	const copy = aboutCopy(locale);
	const homeHref = locale === 'ko' ? '/ko' : '/';

	return (
		<main id="main-content" className="mx-auto max-w-6xl px-6 py-12 lg:py-16">
			{/* Hero */}
			<section className="grid gap-10 lg:grid-cols-[minmax(0,1.08fr)_minmax(320px,0.92fr)] lg:items-end">
				<div>
					<div className="mb-5 flex items-center gap-2.5 font-mono text-xs uppercase tracking-[0.12em] text-faint">
						<AppLink
							href={homeHref}
							aria-label={copy.backToHome}
							className="transition-colors hover:text-foam"
						>
							~
						</AppLink>
						<span className="text-line2">/</span>
						<span>{copy.navAbout}</span>
					</div>
					<p className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-faint">
						{content.eyebrow}
					</p>
					<h1 className="mt-4 max-w-4xl font-sans text-4xl font-bold leading-tight tracking-tight text-ink sm:text-5xl lg:text-6xl">
						{content.title}
					</h1>
					<p className="mt-6 max-w-2xl font-sans text-lg leading-8 text-muted">
						{content.subtitle}
					</p>
					<div className="mt-8 flex flex-wrap gap-3">
						{content.links.map((link) => {
							const external =
								link.external ?? isExternal(link.href) ?? link.href.startsWith('mailto:');
							const linkClass =
								'rounded-lg border border-line2 px-4 py-2.5 font-mono text-sm text-ink no-underline transition-colors hover:border-foam hover:text-foam';

							return external ? (
								<a
									key={link.href}
									href={link.href}
									target={link.external ? '_blank' : undefined}
									rel={link.external ? 'noopener noreferrer' : undefined}
									className={linkClass}
								>
									{link.label}
								</a>
							) : (
								<AppLink key={link.href} href={link.href} className={linkClass}>
									{link.label}
								</AppLink>
							);
						})}
					</div>
				</div>

				<aside className="rounded-xl border border-line2 bg-surface p-5">
					<div className="flex items-center justify-between gap-4 border-b border-line pb-3">
						<p className="font-mono text-xs uppercase tracking-[0.14em] text-faint">
							{content.visualCaption}
						</p>
						<span className="font-mono text-xs text-foam">live</span>
					</div>
					<div className="mt-5 grid gap-3">
						{content.visualLayers.map((layer, index) => (
							<div key={layer} className="grid grid-cols-[2.5rem_1fr] items-center gap-3">
								<span className="font-mono text-xs text-faint">0{index + 1}</span>
								<div className="h-2 overflow-hidden rounded-sm border border-line bg-highlight-low">
									<div
										className="h-full bg-foam"
										style={{ width: `${Math.min(42 + index * 12, 92)}%` }}
									/>
								</div>
								<span className="col-start-2 font-sans text-sm text-muted">{layer}</span>
							</div>
						))}
					</div>
					<div className="mt-6 grid grid-cols-2 gap-3">
						{content.metrics.map((metric) => (
							<div key={metric.label} className="rounded-lg border border-line2 bg-bg p-3">
								<div className={`font-sans text-xl font-bold ${toneClass[metric.tone]}`}>
									{metric.value}
								</div>
								<div className="mt-1 text-xs leading-relaxed text-faint">{metric.label}</div>
							</div>
						))}
					</div>
				</aside>
			</section>

			{/* Intro */}
			<section className="mt-14 grid gap-5 font-sans text-base leading-8 text-muted lg:grid-cols-2">
				{content.intro.map((paragraph) => (
					<p key={paragraph}>{paragraph}</p>
				))}
			</section>

			{/* Career arc */}
			<section className="mt-16">
				<SecHead label={content.sections.arc} />
				<div className="grid gap-4 lg:grid-cols-4">
					{content.timeline.map((item) => (
						<article
							key={item.year}
							className="rounded-lg border border-line2 bg-surface p-5 transition-colors hover:border-foam"
						>
							<p className="font-mono text-xs text-foam">{item.year}</p>
							<h3 className="mt-3 font-sans text-base font-semibold text-ink">{item.title}</h3>
							<p className="mt-3 font-sans text-sm leading-7 text-muted">{item.body}</p>
						</article>
					))}
				</div>
			</section>

			{/* Now */}
			<section className="mt-16 grid gap-8 lg:grid-cols-[0.8fr_1.2fr]">
				<div>
					<SecHead label={content.sections.now} />
					<p className="max-w-sm font-sans text-sm leading-7 text-muted">{copy.nowLead}</p>
				</div>
				<div className="grid gap-4 sm:grid-cols-3">
					{content.now.map((item) => (
						<article
							key={item.title}
							className="rounded-lg border border-line2 bg-surface p-5 transition-colors hover:border-foam"
						>
							<h3 className="font-sans text-base font-semibold text-ink">{item.title}</h3>
							<p className="mt-3 font-sans text-sm leading-7 text-muted">{item.body}</p>
						</article>
					))}
				</div>
			</section>

			{/* Systems */}
			<section className="mt-16">
				<SecHead label={content.sections.systems} />
				<div className="grid gap-4 lg:grid-cols-3">
					{content.systems.map((system) => {
						const external = isExternal(system.href);
						const cardContent = (
							<>
								<img
									src={system.image}
									alt={system.alt}
									className="aspect-[16/9] w-full object-cover"
								/>
								<div className="p-5">
									<p className="font-mono text-xs uppercase tracking-[0.14em] text-faint">
										{system.kicker}
									</p>
									<h3 className="mt-2 font-sans text-lg font-semibold transition-colors group-hover:text-foam">
										{system.title}
									</h3>
									<p className="mt-3 font-sans text-sm leading-7 text-muted">{system.body}</p>
								</div>
							</>
						);
						const cardClass =
							'group block overflow-hidden rounded-lg border border-line2 bg-surface text-ink no-underline transition-colors hover:border-foam';

						return external ? (
							<a
								key={system.title}
								href={system.href}
								target="_blank"
								rel="noopener noreferrer"
								className={cardClass}
							>
								{cardContent}
							</a>
						) : (
							<AppLink key={system.title} href={system.href} className={cardClass}>
								{cardContent}
							</AppLink>
						);
					})}
				</div>
			</section>

			{/* Principles + Learning */}
			<section className="mt-16 grid gap-6 lg:grid-cols-[1fr_1fr]">
				<div>
					<SecHead label={content.sections.principles} />
					<div className="grid gap-4">
						{content.principles.map((principle) => (
							<article
								key={principle.title}
								className="rounded-r-lg border-l-2 border-foam bg-surface px-5 py-4"
							>
								<h3 className="font-sans text-base font-semibold text-ink">{principle.title}</h3>
								<p className="mt-2 font-sans text-sm leading-7 text-muted">{principle.body}</p>
							</article>
						))}
					</div>
				</div>

				<div className="rounded-xl border border-line2 bg-surface p-6">
					<p className="font-mono text-xs uppercase tracking-[0.14em] text-gold">
						{content.learning.kicker}
					</p>
					<h2 className="mt-3 font-sans text-2xl font-semibold leading-snug text-ink">
						{content.learning.title}
					</h2>
					<p className="mt-4 font-sans text-sm leading-7 text-muted">{content.learning.body}</p>
					<ul className="mt-5 grid gap-3">
						{content.learning.items.map((item) => (
							<li key={item} className="flex gap-3 font-sans text-sm leading-7 text-muted">
								<span className="mt-2.5 h-1.5 w-1.5 shrink-0 rounded-full bg-foam" />
								<span>{item}</span>
							</li>
						))}
					</ul>
				</div>
			</section>
		</main>
	);
}

export default AboutPage;
