// src/lib/components/System3bBandNode.svelte
<!--
	System3bBandNode.svelte — non-interactive layer lane behind the chips.
	Spans the full graph width; carries the layer name top-left. zIndex -1 so it
	sits behind subsystem chips and pans/zooms with the graph (true swimlane).
-->
<script lang="ts">
	import type { NodeProps } from '@xyflow/svelte';
	let { data }: NodeProps = $props();
</script>

<!-- NOTE: Svelte interpolates {…} inside quoted style: directive values, so
     style:width="{Number(data.width)}px" is valid + render-verified — NOT literal CSS. -->
<div class="s3b-band" style:width="{Number(data.width)}px" style:height="{Number(data.height)}px">
	<span class="lane-label">{data.name}</span>
</div>

<style>
	.s3b-band {
		border: 1px dashed #353535;
		border-radius: 10px;
		background: rgba(45, 45, 45, 0.18);
		pointer-events: none;
	}
	.lane-label {
		position: absolute;
		top: 6px;
		left: 10px;
		font-family: 'JetBrains Mono', ui-monospace, monospace;
		font-size: 11px;
		letter-spacing: 0.04em;
		text-transform: uppercase;
		color: #666666;
		white-space: nowrap;
	}
</style>

// next/src/components/System3bBandNode.tsx
'use client';

import type { NodeProps } from '@xyflow/react';

/**
 * Non-interactive layer lane behind the chips.
 *
 * Spans the full graph width; carries the layer name top-left. zIndex -1 so it
 * sits behind subsystem chips and pans/zooms with the graph (a true swimlane).
 *
 * Ported from System3bBandNode.svelte. Its @xyflow dependency is type-only —
 * `NodeProps` is erased at build — but the COMPONENT is a full rewrite like any
 * other; only the package swap is a re-type. The Svelte original carried a note
 * about interpolation inside quoted `style:` directive values; that is a Svelte
 * idiom with no React counterpart and is deliberately not carried over. React
 * appends `px` to numeric style values itself.
 */
export default function System3bBandNode({ data }: NodeProps) {
	return (
		<div className="s3b-band" style={{ width: Number(data.width), height: Number(data.height) }}>
			<span className="lane-label">{String(data.name)}</span>
		</div>
	);
}
