// src/lib/components/System3bFitView.svelte
<!--
	System3bFitView.svelte — re-fits the viewport whenever `trigger` changes.
	Must render INSIDE <SvelteFlow> so useSvelteFlow() picks up the flow context.
	xyflow's `fitView` prop only fits on initial mount; custom nodes measure
	asynchronously, so we wait for the next frame after the altitude change before
	fitting. Renders nothing.
-->
<script lang="ts">
	import { useSvelteFlow } from '@xyflow/svelte';

	let { trigger }: { trigger: unknown } = $props();
	const { fitView } = useSvelteFlow();

	$effect(() => {
		// read trigger so the effect re-runs on altitude change
		void trigger;
		let raf2 = 0;
		const raf1 = requestAnimationFrame(() => {
			raf2 = requestAnimationFrame(() => {
				fitView({ padding: 0.18, duration: 220 });
			});
		});
		return () => {
			cancelAnimationFrame(raf1);
			cancelAnimationFrame(raf2);
		};
	});
</script>

// next/src/components/System3bFitView.tsx
'use client';

import { useEffect } from 'react';
import { useReactFlow } from '@xyflow/react';

/**
 * Re-fits the viewport whenever `trigger` changes. Renders nothing.
 *
 * Must render INSIDE <ReactFlow> so useReactFlow() picks up the flow store.
 * xyflow's `fitView` prop only fits on initial mount, and custom nodes measure
 * asynchronously, so this waits for the second frame after an altitude change
 * before fitting.
 *
 * Ported from System3bFitView.svelte, where the same job needed a component
 * because useSvelteFlow() had to run inside the flow context. In React the
 * component still exists for the same reason — a hook needs a component to live
 * in — but it is now the whole file: no markup, one effect.
 */
export default function System3bFitView({ trigger }: { trigger: unknown }) {
	const { fitView } = useReactFlow();

	useEffect(() => {
		let raf2 = 0;
		const raf1 = requestAnimationFrame(() => {
			raf2 = requestAnimationFrame(() => {
				void fitView({ padding: 0.18, duration: 220 });
			});
		});
		return () => {
			cancelAnimationFrame(raf1);
			cancelAnimationFrame(raf2);
		};
		// `trigger` is read only to re-run the fit on altitude change.
	}, [trigger, fitView]);

	return null;
}
