// next/src/components/System3bFlow.tsx
'use client';

import { useCallback, useMemo, useState } from 'react';
import {
	Background,
	Controls,
	MiniMap,
	ReactFlow,
	ReactFlowProvider,
	type Edge,
	type Node,
	type NodeTypes,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';

import {
	BAND_H,
	EDGE_STYLE,
	KIND_STYLE,
	buildDrilldown,
	buildOverview,
	dimEdges,
	kindStyle,
	type FlowModel,
	type SnapEdge,
	type SnapLayer,
	type SnapNode,
} from '../graph/system3b-graph';
import System3bBandNode from './System3bBandNode';
import System3bFitView from './System3bFitView';
import System3bNode from './System3bNode';
import { useGraphCopy } from './System3bLocale';

/**
 * The interactive @xyflow/react graph (CLIENT-ONLY).
 *
 * Loaded lazily by System3bGraph so @xyflow never reaches the prerendered
 * shell. Overview = 11 subsystem chips in 6 layer lanes + 21 aggregated edges;
 * click a chip to drill down to its member nodes and real edges.
 *
 * THIS FILE IS THE LAZY CHUNK ROOT. The @xyflow import, its stylesheet, and
 * ReactFlowProvider all live here and nowhere above: importing any of them from
 * the wrapper would make @xyflow a static dependency of the eagerly loaded
 * chunk and silently defeat the whole lazy boundary while every other check
 * still passed.
 */

/**
 * Module scope, not inside the component. React Flow remounts custom nodes when
 * the nodeTypes identity changes, so building this per render would tear down
 * and rebuild every chip on each state change.
 */
const nodeTypes = {
	subsystem: System3bNode,
	leaf: System3bNode,
	band: System3bBandNode,
} satisfies NodeTypes;

const PRO_OPTIONS = { hideAttribution: true } as const;

const FLOW_BG = '#13111c'; // --bg
const FLOW_BG2 = '#191724'; // --bg2
const FLOW_OVERLAY = '#26233a'; // --overlay
const FLOW_MASK = 'rgba(19, 17, 28, 0.6)'; // --bg @ 0.6 opacity

export interface System3bFlowProps {
	nodes: SnapNode[];
	edges: SnapEdge[];
	layers: SnapLayer[];
}

function mmColor(n: Node): string {
	if (n.type === 'band') return 'transparent';
	return kindStyle(String((n.data as Record<string, unknown>)?.kind)).color;
}

export default function System3bFlow({
	nodes: snapNodes,
	edges: snapEdges,
	layers,
}: System3bFlowProps) {
	const copy = useGraphCopy();
	const [expandedSubKey, setExpandedSubKey] = useState<string | null>(null);
	const [hovered, setHovered] = useState<string | null>(null);

	const model: FlowModel = useMemo(
		() =>
			expandedSubKey
				? buildDrilldown(snapNodes, snapEdges, layers, expandedSubKey)
				: buildOverview(snapNodes, snapEdges, layers),
		[snapNodes, snapEdges, layers, expandedSubKey],
	);

	const expandedName = useMemo(() => {
		if (!expandedSubKey) return null;
		return (
			snapNodes.find((n) => n.subsystem === expandedSubKey && n.kind === 'subsystem')?.name ??
			expandedSubKey
		);
	}, [snapNodes, expandedSubKey]);

	/**
	 * Stable identities. If these were rebuilt each render they would land in
	 * every node's `data`, the nodes array would change on hover, and React Flow
	 * would remount the chips — killing the dimming transition the hover exists
	 * to produce. This is the React-side cost of what Svelte got from an $effect
	 * that deliberately did not read `hovered`.
	 */
	const expand = useCallback((key: string) => {
		setExpandedSubKey(key);
		setHovered(null);
	}, []);
	const reset = useCallback(() => {
		setExpandedSubKey(null);
		setHovered(null);
	}, []);
	const setHover = useCallback((v: string | null) => setHovered(v), []);

	// Rebuilds only when the model (altitude) changes — NOT on hover.
	const flowNodes = useMemo<Node[]>(() => {
		const bands = model.bands.map((b) => ({
			id: `band-${b.layer}`,
			type: 'band',
			position: { x: -24, y: b.y - 26 },
			data: { name: b.name, width: model.width + 48, height: BAND_H - 14 },
			draggable: false,
			selectable: false,
			zIndex: -1,
		}));
		const chips = model.nodes.map((n) => ({
			...n,
			data: { ...n.data, onExpand: expand, onHover: setHover },
		}));
		return [...bands, ...chips] as unknown as Node[];
	}, [model, expand, setHover]);

	// Re-styles edges on hover (dims non-incident) without rebuilding nodes.
	const flowEdges = useMemo<Edge[]>(
		() => dimEdges(model.edges, hovered) as unknown as Edge[],
		[model, hovered],
	);

	return (
		<div className="s3b-flow">
			<div className="toolbar">
				<span className="title">
					{expandedSubKey ? (
						<>
							<span className="crumb">&#9656;</span> {expandedName}
						</>
					) : (
						copy.overview
					)}
				</span>
				<div className="spacer" />
				{expandedSubKey ? (
					<button type="button" className="btn" onClick={reset}>
						&#8592; {copy.back}
					</button>
				) : (
					<span className="hint">{copy.expandHint}</span>
				)}
			</div>

			<div className="canvas">
				<ReactFlowProvider>
					<ReactFlow
						nodes={flowNodes}
						edges={flowEdges}
						nodeTypes={nodeTypes}
						colorMode="dark"
						fitView
						nodesDraggable={false}
						nodesConnectable={false}
						elementsSelectable={false}
						minZoom={0.3}
						maxZoom={1.6}
						proOptions={PRO_OPTIONS}
					>
						<Background bgColor={FLOW_BG} color={FLOW_OVERLAY} gap={22} />
						<Controls showInteractive={false} />
						<MiniMap
							pannable
							zoomable
							nodeColor={mmColor}
							maskColor={FLOW_MASK}
							bgColor={FLOW_BG2}
						/>
						<System3bFitView trigger={expandedSubKey} />
					</ReactFlow>
				</ReactFlowProvider>
			</div>

			<div className="legend">
				<div className="legend-row">
					<span className="legend-head">{copy.nodesLabel}</span>
					{Object.entries(KIND_STYLE).map(([kind, s]) => (
						<span className="chip" key={kind}>
							<span className="swatch" style={{ background: s.color }} />
							{copy.kindLabel[kind] ?? s.label}
						</span>
					))}
				</div>
				<div className="legend-row">
					<span className="legend-head">{copy.relationsLegend}</span>
					{Object.entries(EDGE_STYLE).map(([kind, s]) => (
						<span className="chip" key={kind}>
							<span
								className="line"
								style={{ borderTop: `2px ${s.dash ? 'dashed' : 'solid'} ${s.color}` }}
							/>
							{copy.edgeLabel[kind] ?? s.label}
						</span>
					))}
				</div>
			</div>
		</div>
	);
}

// src/lib/components/System3bFlow.svelte
<!--
	System3bFlow.svelte — the interactive @xyflow/svelte graph (CLIENT-ONLY).
	Loaded lazily by System3bGraph.svelte so @xyflow never reaches the prerendered
	shell. Overview = 11 subsystem chips in 6 layer lanes + 21 aggregated edges;
	click a chip → drill down to its member nodes + real edges.
	Data source = the already-sanitized snapshot props (no new 3B reads).
-->
<script lang="ts">
	import { SvelteFlow, Background, Controls, MiniMap, type Node, type Edge } from '@xyflow/svelte';
	import '@xyflow/svelte/dist/style.css';
	import { m } from '$lib/paraglide/messages';
	import System3bNode from './System3bNode.svelte';
	import System3bBandNode from './System3bBandNode.svelte';
	import FitView from './System3bFitView.svelte';
	import {
		buildOverview,
		buildDrilldown,
		kindStyle,
		KIND_STYLE,
		EDGE_STYLE,
		BAND_H,
		type SnapNode,
		type SnapEdge,
		type SnapLayer,
		type FlowModel,
	} from '$lib/utils/system3b-graph';

	interface Props {
		nodes: SnapNode[];
		edges: SnapEdge[];
		layers: SnapLayer[];
		locale?: 'en' | 'ko';
	}
	let { nodes: snapNodes, edges: snapEdges, layers }: Props = $props();

	const nodeTypes = {
		subsystem: System3bNode,
		leaf: System3bNode,
		band: System3bBandNode,
	} as const;

	let expandedSubKey = $state<string | null>(null);
	let hovered = $state<string | null>(null);

	const model: FlowModel = $derived(
		expandedSubKey
			? buildDrilldown(snapNodes, snapEdges, layers, expandedSubKey)
			: buildOverview(snapNodes, snapEdges, layers),
	);
	const expandedName = $derived(
		expandedSubKey
			? (snapNodes.find((n) => n.subsystem === expandedSubKey && n.kind === 'subsystem')?.name ??
					expandedSubKey)
			: null,
	);

	function expand(key: string) {
		expandedSubKey = key;
		hovered = null;
	}
	function reset() {
		expandedSubKey = null;
		hovered = null;
	}
	function setHover(v: string | null) {
		hovered = v;
	}

	let flowNodes = $state.raw<Node[]>([]);
	let flowEdges = $state.raw<Edge[]>([]);

	// Rebuild nodes only when the model (altitude) changes — NOT on hover.
	$effect(() => {
		const bands: Node[] = model.bands.map((b) => ({
			id: `band-${b.layer}`,
			type: 'band',
			position: { x: -24, y: b.y - 26 },
			data: { name: b.name, width: model.width + 48, height: BAND_H - 14 },
			draggable: false,
			selectable: false,
			zIndex: -1,
		})) as unknown as Node[];
		const chips: Node[] = model.nodes.map((n) => ({
			...n,
			data: { ...n.data, onExpand: expand, onHover: setHover },
		})) as unknown as Node[];
		flowNodes = [...bands, ...chips];
	});

	// Re-style edges on hover (dim non-incident) without rebuilding nodes.
	$effect(() => {
		const h = hovered;
		flowEdges = model.edges.map((e) => {
			const incident = !h || e.source === h || e.target === h;
			return {
				...e,
				style: incident ? e.style : `${e.style};opacity:0.1`,
				animated: incident ? e.animated : false,
			};
		}) as unknown as Edge[];
	});

	function mmColor(n: Node): string {
		if (n.type === 'band') return 'transparent';
		return kindStyle(String((n.data as Record<string, unknown>)?.kind)).color;
	}
</script>

<div class="s3b-flow">
	<div class="toolbar">
		<span class="title">
			{#if expandedSubKey}<span class="crumb">▸</span> {expandedName}{:else}{m.system_3b_graph_overview()}{/if}
		</span>
		<div class="spacer"></div>
		{#if expandedSubKey}
			<button type="button" class="btn" onclick={reset}>← {m.system_3b_graph_back()}</button>
		{:else}
			<span class="hint">{m.system_3b_graph_expand_hint()}</span>
		{/if}
	</div>

	<div class="canvas">
		<SvelteFlow
			bind:nodes={flowNodes}
			bind:edges={flowEdges}
			{nodeTypes}
			colorMode="dark"
			fitView
			nodesDraggable={false}
			nodesConnectable={false}
			elementsSelectable={false}
			minZoom={0.3}
			maxZoom={1.6}
			proOptions={{ hideAttribution: true }}
		>
			<Background bgColor="#1a1a1a" patternColor="#2b2b2b" gap={22} />
			<Controls showLock={false} />
			<MiniMap pannable zoomable nodeColor={mmColor} maskColor="rgba(10,10,10,0.6)" bgColor="#161616" />
			<FitView trigger={expandedSubKey} />
		</SvelteFlow>
	</div>

	<div class="legend">
		<div class="legend-row">
			<span class="legend-head">{m.system_3b_nodes_label()}</span>
			{#each Object.entries(KIND_STYLE) as [kind, s] (kind)}
				<span class="chip"><span class="swatch" style:background={s.color}></span>{s.label}</span>
			{/each}
		</div>
		<div class="legend-row">
			<span class="legend-head">{m.system_3b_graph_relations_legend()}</span>
			{#each Object.entries(EDGE_STYLE) as [kind, s] (kind)}
				<span class="chip"
					><span
						class="line"
						style:background={s.color}
						style:opacity={s.dash ? 0.7 : 1}
					></span>{s.label}</span
				>
			{/each}
		</div>
	</div>
</div>

<style>
	.s3b-flow {
		border: 1px solid #404040;
		border-radius: 12px;
		overflow: hidden;
		background: #1a1a1a;
	}
	.toolbar {
		display: flex;
		align-items: center;
		gap: 12px;
		padding: 10px 14px;
		border-bottom: 1px solid #404040;
		background: #2d2d2d;
		font-family: 'JetBrains Mono', ui-monospace, monospace;
		font-size: 12px;
	}
	.title {
		color: #e5e5e5;
	}
	.crumb {
		color: #da7756;
	}
	.spacer {
		flex: 1;
	}
	.hint {
		color: #666666;
	}
	.btn {
		background: #1a1a1a;
		border: 1px solid #404040;
		border-radius: 6px;
		color: #e5e5e5;
		font: inherit;
		padding: 4px 10px;
		cursor: pointer;
	}
	.btn:hover {
		border-color: #da7756;
		color: #da7756;
	}
	.canvas {
		height: clamp(440px, 70vh, 760px);
		width: 100%;
	}
	.legend {
		display: flex;
		flex-direction: column;
		gap: 8px;
		padding: 10px 14px;
		border-top: 1px solid #404040;
		background: #2d2d2d;
		font-family: 'JetBrains Mono', ui-monospace, monospace;
		font-size: 11px;
	}
	.legend-row {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		gap: 10px;
	}
	.legend-head {
		color: #666666;
		text-transform: uppercase;
		letter-spacing: 0.05em;
		min-width: 64px;
	}
	.chip {
		display: inline-flex;
		align-items: center;
		gap: 5px;
		color: #888888;
	}
	.swatch {
		width: 9px;
		height: 9px;
		border-radius: 2px;
		display: inline-block;
	}
	.line {
		width: 16px;
		height: 2px;
		border-radius: 2px;
		display: inline-block;
	}
	/* xyflow surface tweaks to match the terminal palette */
	.canvas :global(.svelte-flow) {
		background: #1a1a1a;
	}
	.canvas :global(.svelte-flow__controls-button) {
		background: #2d2d2d;
		border-bottom: 1px solid #404040;
		fill: #e5e5e5;
		color: #e5e5e5;
	}
	.canvas :global(.svelte-flow__controls-button:hover) {
		background: #353535;
	}
	.canvas :global(.svelte-flow__edge-path) {
		transition: opacity 120ms ease;
	}
</style>
